#!/bin/bash
set -e

# Prompt user for test description
echo "🤖 QA Persona: Test Generator"
echo "Describe the test scenario you want to create (e.g., 'Login with invalid email'):"
read -p "> " DESCRIPTION

# Convert description to safe filename
FILENAME=$(echo "$DESCRIPTION" | tr '[:upper:]' '[:lower:]' | tr -cd '[a-z0-9-_ ]' | tr ' ' '-')
FILEPATH="ui/tests/${FILENAME}.spec.ts"

if [ -f "$FILEPATH" ]; then
    echo "Error: File $FILEPATH already exists."
    exit 1
fi

echo "Creating scaffold at $FILEPATH..."

cat > "$FILEPATH" <<EOF
import { test, expect } from '@playwright/test';
import { userPassLogin } from './helpers/login';

/**
 * SCENARIO: $DESCRIPTION
 * Generated by QA Persona
 */
test.describe('${DESCRIPTION}', () => {

    test('should behave as expected', async ({ page }) => {
        // 1. Arrange
        await page.goto('/ui/login');

        // 2. Act
        // TODO: Implement steps for '$DESCRIPTION'
        
        // 3. Assert
        
    });
});
EOF

echo "✅ Scaffold created!"
echo ""
echo "To accelerate development:"
echo "1. Run 'npx playwright codegen http://localhost/ui/login' to record your actions on the live site."
echo "2. Copy the generated steps."
echo "3. Paste them into '$FILEPATH'."
echo "4. Use Copilot to refactor them into reusable functions."
echo ""
echo "Or use Copilot directly:"
echo "1. Open $FILEPATH"
echo "2. Place cursor inside the test body."
echo "3. Open Copilot Chat (Ctrl+I or Panel) and ask:"
echo "   'Implement the test steps for \"$DESCRIPTION\" using the page object model.'"
echo ""
