CREATE USER hydra WITH PASSWORD 'hydra';

CREATE DATABASE hydra;
GRANT ALL PRIVILEGES ON DATABASE hydra TO hydra;
ALTER DATABASE hydra OWNER TO hydra;

CREATE USER kratos WITH PASSWORD 'kratos';

CREATE DATABASE kratos;
GRANT ALL PRIVILEGES ON DATABASE kratos TO kratos;
ALTER DATABASE kratos OWNER TO kratos;
