version: '3.7'
include:
  - docker-compose.dev.yml
services:
  identity-platform-login-ui:
    image: ghcr.io/canonical/identity-platform-login-ui:main
    environment:
      - KRATOS_PUBLIC_URL=http://localhost:4433
      - HYDRA_ADMIN_URL=http://localhost:4445
      - BASE_URL=http://localhost:4455
      - COOKIES_ENCRYPTION_KEY=WrfOcYmVBwyduEbKYTUhO4X7XVaOQ1wF
      - PORT=4455
      - LOG_LEVEL=DEBUG
      - LOG_FILE=/var/log/aba.log
      - TRACING_ENABLED=FALSE
      - AUTHORIZATION_ENABLED=FALSE
    ports:
      - "4455:4455"
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
