// Copyright 2026 Canonical Ltd.
// SPDX-License-Identifier: AGPL-3.0

package tenants

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"time"

	kClient "github.com/ory/kratos-client-go/v25"

	"github.com/canonical/identity-platform-login-ui/internal/logging"
	"github.com/canonical/identity-platform-login-ui/internal/monitoring"
	"github.com/canonical/identity-platform-login-ui/internal/tracing"
)

// Tenant represents a tenant entry returned by the external tenants API.
type Tenant struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
}

// ResolveResult is the outcome of the tenant resolution decision.
// When RedirectTo is non-empty, the caller should redirect the user there.
// When RedirectTo is empty, the caller should proceed with the original flow.
// TenantID is non-empty when exactly one tenant was found; the handler must
// store it in the session cookie and build an appropriate redirect itself.
// It is intentionally excluded from JSON serialisation.
type ResolveResult struct {
	RedirectTo string `json:"redirect_to,omitempty"`
	TenantID   string `json:"-"`
}

// Service fetches tenant data from the external tenants API.
// TODO: Replace the ad-hoc HTTP client with the autogenerated SDK when the
// tenant service exposes a gRPC endpoint.
type Service struct {
	tenantsAPIURL string
	baseURL       string
	httpClient    *http.Client
	flowFetcher   FlowFetcherInterface

	tracer  tracing.TracingInterface
	monitor monitoring.MonitorInterface
	logger  logging.LoggerInterface
}

func (s *Service) lookupTenantsByEmail(ctx context.Context, email string) ([]Tenant, error) {
	ctx, span := s.tracer.Start(ctx, "tenants.Service.lookupTenantsByEmail")
	defer span.End()

	requestURL := fmt.Sprintf("%s/api/v0/tenants/lookup?email=%s", s.tenantsAPIURL, url.QueryEscape(email))

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	resp, err := s.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch tenants: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("tenants API returned status %d", resp.StatusCode)
	}

	var wrapper struct {
		Tenants []Tenant `json:"tenants"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&wrapper); err != nil {
		return nil, fmt.Errorf("failed to decode tenants response: %w", err)
	}

	return wrapper.Tenants, nil
}

// LookupTenantsByEmail looks up tenants for the given email address directly,
// without requiring a Kratos login flow. This is used when the user already
// has an active Kratos session and a flow has not yet been created.
func (s *Service) LookupTenantsByEmail(ctx context.Context, email string) ([]Tenant, error) {
	return s.lookupTenantsByEmail(ctx, email)
}

// LookupTenantsByFlow fetches the Kratos login flow, extracts the email from
// the flow's UI nodes, and looks up tenants for that email.
func (s *Service) LookupTenantsByFlow(ctx context.Context, flowID string, cookies []*http.Cookie) ([]Tenant, error) {
	ctx, span := s.tracer.Start(ctx, "tenants.Service.LookupTenantsByFlow")
	defer span.End()

	flow, _, err := s.flowFetcher.GetLoginFlow(ctx, flowID, cookies)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch login flow: %w", err)
	}

	email, err := emailFromFlow(flow)
	if err != nil {
		return nil, err
	}

	return s.lookupTenantsByEmail(ctx, email)
}

// emailFromFlow extracts the email from a login flow's "identifier" UI node.
func emailFromFlow(flow *kClient.LoginFlow) (string, error) {
	for _, node := range flow.Ui.Nodes {
		if node.Type == "input" &&
			node.Attributes.UiNodeInputAttributes != nil &&
			node.Attributes.UiNodeInputAttributes.Name == "identifier" {
			val, ok := node.Attributes.UiNodeInputAttributes.Value.(string)
			if !ok || val == "" {
				return "", fmt.Errorf("identifier value is not a string in flow %s", flow.Id)
			}
			return val, nil
		}
	}
	return "", fmt.Errorf("identifier node not found in flow %s", flow.Id)
}

// ResolveTenant looks up tenants for the given flow and applies the routing
// decision: 0 tenants → proceed, 1 tenant → store cookie + redirect to flow,
// N tenants → redirect to the tenant selection page.
func (s *Service) ResolveTenant(ctx context.Context, flowID string, loginChallenge string, cookies []*http.Cookie) (*ResolveResult, error) {
	ctx, span := s.tracer.Start(ctx, "tenants.Service.ResolveTenant")
	defer span.End()

	tenants, err := s.LookupTenantsByFlow(ctx, flowID, cookies)
	if err != nil {
		return nil, fmt.Errorf("failed to look up tenants: %w", err)
	}

	if len(tenants) == 0 {
		return &ResolveResult{}, nil
	}

	if len(tenants) == 1 {
		// Return the tenant ID; the handler stores it in the cookie and builds
		// the redirect to avoid an extra round-trip through a callback endpoint.
		return &ResolveResult{TenantID: tenants[0].ID}, nil
	}

	return &ResolveResult{
		RedirectTo: s.multiTenantRedirectURL(flowID, loginChallenge),
	}, nil
}

func (s *Service) multiTenantRedirectURL(flowID, loginChallenge string) string {
	params := url.Values{}
	params.Set("flow", flowID)
	params.Set("login_challenge", loginChallenge)
	base, _ := url.JoinPath(s.baseURL, "/ui/select_tenant")
	return base + "?" + params.Encode()
}

func NewService(tenantsAPIURL string, baseURL string, flowFetcher FlowFetcherInterface, tracer tracing.TracingInterface, monitor monitoring.MonitorInterface, logger logging.LoggerInterface) *Service {
	return &Service{
		tenantsAPIURL: tenantsAPIURL,
		baseURL:       baseURL,
		httpClient:    &http.Client{Timeout: 30 * time.Second},
		flowFetcher:   flowFetcher,
		tracer:        tracer,
		monitor:       monitor,
		logger:        logger,
	}
}
