# Stage 1: Build static Next.js export
FROM node:22-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy application code
COPY . .

# Build argument for backend API URL (defaults to relative or reverse proxy path)
ARG NEXT_PUBLIC_API_URL=""
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

# Build Next.js static export (outputs to ./dist)
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:1.25-alpine AS runner

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy static assets generated by Next.js
COPY --from=builder /app/dist /usr/share/nginx/html/ui

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
