name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: canonical/craft-actions/rockcraft-pack@main
      id: rockcraft
    - uses: actions/upload-artifact@v3
      with:
        name: identity-platform-login-ui-rock
        path: ${{ steps.rockcraft.outputs.rock }}

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    - name: Create SBOM
      run: syft $(realpath ./identity-platform-login-ui_*.rock) -o spdx-json=identity_platform_login_ui.sbom.json

    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: identity-platform-login-ui-sbom
        path: "identity_platform_login_ui.sbom.json"

