name: ci
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release-**"
    tags:
      - "v**"
  pull_request:
    branches:
      - "*"


jobs:
  unit-test:
    uses: ./.github/workflows/unittest.yaml
  e2e-test:
    uses: ./.github/workflows/e2etest.yaml

  get-architectures:
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.parse.outputs.architectures }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Parse platforms from rockcraft.yaml
        id: parse
        run: |
          archs=$(yq -o=json -I=0 '.platforms | keys' rockcraft.yaml)
          echo "Found architectures: $archs"
          echo "architectures=$archs" >> "$GITHUB_OUTPUT"

  build:
    needs: get-architectures
    strategy:
      matrix:
        architecture: ${{ fromJson(needs.get-architectures.outputs.architectures) }}
    uses: canonical/identity-team/.github/workflows/_rock-build.yaml@d64b860c8679d3539f5f35f3d2494c419d8e41b5 # v1.12.2
    with:
      structure-tests-enabled: true
      architecture: ${{ matrix.architecture }}

  gh-publish:
    permissions:
      packages: write
      contents: read
    if: ${{ (github.ref == 'refs/heads/main') || (github.ref_type == 'tag') }}
    needs: [ build, unit-test ]
    uses: canonical/identity-team/.github/workflows/_rock-gh-publish.yaml@d64b860c8679d3539f5f35f3d2494c419d8e41b5 # v1.12.2

  oci-publish:
    # only release to oci-factory in case of release
    if: github.ref_type == 'tag'
    needs: [ build, unit-test ]
    uses: canonical/identity-team/.github/workflows/_rock-oci-publish.yaml@d64b860c8679d3539f5f35f3d2494c419d8e41b5 # v1.12.2
    with:
      eol-stable-release: "6 month"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  scan:
    permissions:
      packages: read
      contents: read
      security-events: write
      actions: read
    if: ${{ (github.ref == 'refs/heads/main') || (github.ref_type == 'tag') }}
    needs: gh-publish
    uses: canonical/identity-team/.github/workflows/_rock-scan.yaml@d64b860c8679d3539f5f35f3d2494c419d8e41b5 # v1.12.2
    with:
      image: ${{ needs.gh-publish.outputs.image }}

  oci-update-pr:
    needs: [gh-publish, scan]
    if: github.ref_type == 'tag'
    permissions:
      contents: write
      pull-requests: write
    uses: canonical/identity-team/.github/workflows/oci-update-pr.yaml@d64b860c8679d3539f5f35f3d2494c419d8e41b5 # v1.12.2
    with:
        oci-image: ${{ needs.gh-publish.outputs.image }}
        repository: canonical/identity-platform-login-ui-operator
    secrets:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}