name: CVEs checker

on:
  workflow_dispatch:
  issues:
    types: [opened]
  schedule:
     - cron: '0 0 * * 0'

jobs:
    list-all-issues:
        outputs:
            issues: ${{ steps.issues.outputs.ids }}
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'schedule' }}
        steps:
          - run: |
              ids=$(gh issue list --json number,author -q '[.[] | select(.author.login == "ROCKsBot") | .number]')
              echo "ids=${ids}" >> $GITHUB_OUTPUT
            id: issues
            env:
                GH_PAGER:
                GH_TOKEN: ${{ github.token }}
                GH_REPO: ${{ github.repository }}

    scheduled-check:
        if: ${{ github.event_name == 'schedule' && needs.list-all-issues.outputs.issues != '[]' && needs.list-all-issues.outputs.issues != '' }}
        permissions:
            contents: write
            issues: write
        strategy:
            matrix:
                issue: ${{ fromJson(needs.list-all-issues.outputs.issues) }}
        needs:
            - list-all-issues
        uses: canonical/identity-team/.github/workflows/cve-check.yaml@fc85af7448538c473be450dc2c8ec5d158ea0d15 # v1.17.0
        with:
            issue: ${{ matrix.issue }}

    apply-labels:
        permissions:
            contents: write
            issues: write
        uses: canonical/identity-team/.github/workflows/cve-check.yaml@fc85af7448538c473be450dc2c8ec5d158ea0d15 # v1.17.0
        if: ${{ github.event.issue.id }}

    scan-stable:
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        permissions:
            packages: read
            contents: read
            security-events: write
            actions: read
        uses: canonical/identity-team/.github/workflows/_rock-scan.yaml@fc85af7448538c473be450dc2c8ec5d158ea0d15 # v1.17.0
        with:
            image: ${{ vars.REGISTRY || 'ghcr.io' }}/${{ github.repository }}:stable
            exit-code: '0'
            severity: 'HIGH,CRITICAL'
            ignore-unfixed: true
            trivyignores: '.trivyignore'
