name: On Main Push

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    uses: ./.github/workflows/unittest.yaml
  build:
    needs: unit-test
    uses: ./.github/workflows/build.yaml
  publish:
    needs: build
    uses: ./.github/workflows/publish.yaml
  scan:
    needs: publish
    uses: ./.github/workflows/scan.yaml