# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3cef36a9aba515d8726b491905b3bc766832e221 # v39.0.5
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.PAT_TOKEN }}
