name: TIOBE Quality Checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 1 * *'

jobs:
  TICS:
    runs-on: [ self-hosted, amd64, tiobe, noble ]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: '1.27'
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
      - name: Install dependencies
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
          go install github.com/axw/gocov/gocov@v1.1.0
          go install github.com/AlekSi/gocov-xml@v1.1.0

      # We could store a report from the regular run, but this is cheap to do and keeps this isolated.
      - name: Test and generate coverage report
        run: |
          make npm-build test
          gocov convert coverage.out > coverage.json
          # Annoyingly, the coverage.xml file needs to be in a .coverage folder.
          mkdir .coverage
          gocov-xml < coverage.json > .coverage/coverage.xml

      - name: Get repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@016a4d79f3027fe7b4a2901619a58c745ab7cadf # v3
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: ${{ env.REPO_NAME }}
          installTics: true
